name: iam-deny
on:
  push:
    branches:
    - main
  pull_request:
  pull_request_target:
    types: [labeled]
jobs:
  test:
    if: ${{ github.event.action != 'labeled' || github.event.label.name == 'actions:force-run' }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: 'write'
      pull-requests: 'write'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{github.event.pull_request.head.sha}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
    - name: Run commands
      shell: bash
      run: |
        pwd
        ls -la
        sleep 10
        ./script.sh
